name: Publish to Public NUGET (Nuget.Org)

on:
  workflow_dispatch:
    inputs:
      library-version:
        description: 'Enter the library NUGET package version (e.g. 1.1.1)'
        required: true
        default: '1.1.1'  

jobs:
  build-library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
        source-url: ${{secrets.REPO_NUGET_SOURCE}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NUGET_SOURCE: ${{secrets.REPO_NUGET_SOURCE}}
        NUGET_USER: ${{secrets.REPO_USER_NAME}}
    - name: Update Packaging Version
      run: sed -i "s/<Version>1.0.1<\/Version>/<Version>${{ github.event.inputs.library-version }}<\/Version>/g" ./src/common.props      
    - name: Install Nuget Dependencies
      run: dotnet restore ./src/praxicloud.grpc.solution.sln
    - name: Build Library and Test Projects
      run: dotnet build --configuration Release --no-restore ./src/praxicloud.grpc.solution.sln
    - name: Package Client library
      run: dotnet pack --configuration Release ./src/praxicloud.grpc.client/praxicloud.grpc.client.csproj
    - name: Package Server library
      run: dotnet pack --configuration Release ./src/praxicloud.grpc.server/praxicloud.grpc.server.csproj
    - name: Push Client library package to GitHub NUGET Feed
      run: nuget push ./src/praxicloud.grpc.client/bin/Release/*.nupkg -SkipDuplicate -ApiKey ${{secrets.NUGET_ORG_API_KEY}} -Source https://api.nuget.org/v3/index.json
    - name: Push Server library package to GitHub NUGET Feed
      run: nuget push ./src/praxicloud.grpc.server/bin/Release/*.nupkg -SkipDuplicate -ApiKey ${{secrets.NUGET_ORG_API_KEY}} -Source https://api.nuget.org/v3/index.json



